/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsultantsRouteImport } from './routes/consultants'
import { Route as IndexRouteImport } from './routes/index'

const ConsultantsRoute = ConsultantsRouteImport.update({
  id: '/consultants',
  path: '/consultants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultants': typeof ConsultantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultants': typeof ConsultantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultants': typeof ConsultantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consultants'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consultants'
  id: '__root__' | '/' | '/consultants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultantsRoute: typeof ConsultantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/consultants': {
      id: '/consultants'
      path: '/consultants'
      fullPath: '/consultants'
      preLoaderRoute: typeof ConsultantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultantsRoute: ConsultantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
