// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { bearerToken, verifySupabaseToken } from "./auth.server";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const token = bearerToken(request);
    if (!token) {
      throw new Error("Unauthorized: Invalid token");
    }

    const { supabase, claims, userId } = await verifySupabaseToken(token);

    return next({
      context: {
        supabase,
        userId,
        claims,
      },
    });
  },
);
